### ISSUE TITLE
既然插入一次代码即可禁止dex2jar，那么支持通过注解标记需要保护的方法的意义何在？

### ISSUE THREAD

**Issue by gflkdns** [Ivonhoe/dexguard#4]

**Comment by Ivonhoe** [comment]
这个工具是对dex2jar的防护，通过在jar--->dex编译流程里，插入字节码保护method。
之前版本是通过map配置文件来配置需要被保护的类和method信息，现在可以支持在代码中用注解标记需要被保护的method。

**Comment by gflkdns** [comment]
明白了，多谢
